### ISSUE TITLE
HTTP Functions not working on recent Wiremod releases

### ISSUE THREAD

**Issue by kaneiskewl** [GrimKriegor/assistant#4] opened 2016-07-27 21:39 UTC
> no such function: runOnHTTP(number) at line 286 char 5

not sure why im getting this error could use some help resolving this asap

**Comment by kaneiskewl** [comment] 2016-07-27 21:55
edit runOnHTTP(normal) at line 286 char 5

**Comment by GrimKriegor** [comment] 2016-07-27 22:48
Hello there @kaneiskewl and thanks for your interest in the assistant.

Allow me to ask, when did you first notice this issue?

I've just tested and it seems the [HTTP functions](https://github.com/wiremod/wire/wiki/Expression-2#HTTP_Functions) aren't working on the latest Wiremod.

I've reverted back to a few older commits of Wiremod and it seems something must have changed between late 2015 and early 2016 making the HTTP functions unusable or removing them altogether.

That is unfortunate and I'll have to check out what really happened.

For now I've prepared you an assistant without the updater that should work for now:
[grim's_assistant_v15-803_nohttp.txt](https://github.com/GrimKriegor/assistant/files/387330/grim.s_assistant_v15-803_nohttp.txt)

If you know anything about possible recent changes to Wiremod lemme know, seems odd they would just remove such useful features.

**Comment by kaneiskewl** [comment] 2016-07-28 01:28
thank you :) and unfortunately I know nothing about the wiremod update

**Comment by GrimKriegor** [comment] 2017-10-07 05:09
Caused by default upstream behavior

https://github.com/wiremod/wire/commit/9f4c8f0474499abf62023da31a2799864cc2fe83#diff-3f0108ca87e56d02ecdd492488a21e8b

**Comment by GrimKriegor** [comment] 2017-10-07 06:02
Fixed by https://github.com/GrimKriegor/assistant/commit/306cf8a6cd441b74191e80d7999177a6f4b36eda

Requires server owners to activate the Wire HTTP Functions extension.

    wire_expression2_extension_enable http

**Closed as completed by GrimKriegor** 2017-10-07 06:02 UTC
Labels: bug, upstream issue
